image: python:3.8

stages:
  - setup
  - download
  - build
  - deploy

variables:
  TZ: "America/Sao_Paulo"

cache:
  paths:
    - node_modules/

setup:
  stage: setup
  image: node:14
  script:
    - npm install
    - node generate_metadata.js
  artifacts:
    paths:
      - files_metadata.json
    expire_in: 1 hour

download:
  stage: download
  before_script:
    - pip install requests
  script:
    - python playlists.py
  artifacts:
    paths:
      - "*.m3u"
      - "*.xml.gz"
    expire_in: 1 week

build:
  stage: build
  image: node:14
  script:
    - echo "Arquivos já estão no diretório raiz"
    - ls -la
  artifacts:
    paths:
      - "*.html"
      - "*.css"
      - "*.js"
      - "*.json"
      - "*.m3u"
      - "*.xml.gz"
    expire_in: 1 week

pages:
  stage: deploy
  dependencies:
    - setup
    - download
    - build
  script:
    - echo "Preparando diretório public..."
    - mkdir -p public
    - cp -r *.html *.css *.js *.json *.m3u *.xml.gz public/ 2>/dev/null || true
    - echo "Conteúdo do diretório public:"
    - ls -la public/
  artifacts:
    paths:
      - public
    expire_in: 1 week